# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      ### - image: circleci/golang:1.10.3
      - image: jojomi/hugo

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo

    working_directory: /home/circleci/src/github.com/koura718/
    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: 
          name: Set PATH to .bashrc.
          command: |
            echo 'export PATH=$HOME/go/bin:$HOME/go_appengine:$PATH' >> $BASH_ENV
            source /home/circleci/.bashrc
            echo $HOME
            date
            hugo version
